version: '3.8'

services:
  database:
    image: postgres:17.6
    container_name: poll_tes
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '${DB_PORT}:5432'
    restart: always
    tty: true

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_tes
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  app1:
    image: poll_app
    container_name: poll_app1
    ports:
      - '3005:3000'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  app2:
    image: poll_app
    container_name: poll_app2
    ports:
      - '3008:3000'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
volumes:
  polling-storage:
